services:
  netbird:
    image: netbirdio/netbird:latest
    container_name: netbird
    restart: unless-stopped
    hostname: $HOSTNAME
    env_file:
      - ./client.env
    volumes:
      - netbird-client:/etc/netbird
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - BPF
      - NET_BIND_SERVICE
      - SYS_ADMIN
      - SYS_RESOURCE

volumes:
  netbird-client: